### ISSUE TITLE
edit search engine metadata

### ISSUE THREAD

**Issue by gbinal** [GSA/opioids.gov#78]
When one is [searching and finds opioids.gov](https://www.google.com/search?q=site%3Aopioids.gov&oq=site%3Aopioids.gov&aqs=chrome..69i57j69i58.8394j1j4&sourceid=chrome&ie=UTF-8), the site summary is the first bit of text on the page when we'd want it to be a pithy site summary instead.  

I believe this is managed by the meta description, which is managed with the <description> tag in the site HTML.  

![screen shot 2018-03-23 at 4 03 40 pm](https://user-images.githubusercontent.com/633088/37851192-5222af78-2eb4-11e8-9e4c-0d326391b16a.png)

**Comment by gbinal** [comment]
It looks like this should be governed at https://github.com/GSA/opioids.gov/blob/master/_includes/meta.html#L22 but is not being consumed correctly.  I'd suggest checking with Federalist support to ask about it.

**Comment by saracope** [comment]
Thanks for pointing that out, @gbinal. Looking at this, I think the tag one line 22 is only for open graph sites. I'm going to add in a meta description in the search engine section, that should do it.
